/*
 ============================================================================
 Name        : ultrasonic.h
 Author      : Menna Tullah Medhat
 Description : The ultrasonic sensor emits an ultrasonic wave and listens for
               its reflection from a nearby object
               initialization, turning LEDs on, and turning LEDs off.
 Date        : 13/6/2024
 ============================================================================
 */
#include "ultrasonic.h"
#include "gpio.h"
#include <util/delay.h>
#include "icu.h"

	ICU_ConfigType configuration = {FCPU_8, RISING};

/*global variables declarations*/
static volatile uint16 g_valueOfTime=0;
static volatile uint8 g_counter=0;

/*Initialize the ICU driver as required.
Set up the ICU callback function.
Set the direction for the trigger pin as output through
the GPIO driver*/

/*This is the callback function called by the ICU driver.
It calculates the high time (pulse time) generated by
the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void){
	g_counter++;
	if (g_counter==1)
	{
		ICU_clearTimerValue();
		ICU_setEdgeDetectionType(FALLING);
	}
	else if (g_counter==2)
	{
		g_valueOfTime=ICU_getInputCaptureValue();
		ICU_setEdgeDetectionType(RISING);
		ICU_clearTimerValue();
		g_counter=0;
	}
}

void Ultrasonic_init(void){
	/*The ICU should be configured with a frequency of F_CPU/8 and
	 *  set to detect the rising edge as the first edge*/
	ICU_init(&configuration);

	/*setup the ICU callback function */
	ICU_setCallBack(Ultrasonic_edgeProcessing);
	GPIO_setupPinDirection(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,PIN_OUTPUT);
	/*this step is done at the ICU driver
	 * GPIO_setupPinDirection(ULTRASONIC_ECHO_PORT_ID,ULTRASONIC_ECHO_PIN_ID,PIN_INPUT);
	 */

}

/*Send the trigger pulse to the ultrasonic sensor.*/
static void Ultrasonic_Trigger(void){
	/*Sending the trigger pulse for the trigger pin*/
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_HIGH);
	_delay_us(58);
	GPIO_writePin(ULTRASONIC_TRIGGER_PORT_ID,ULTRASONIC_TRIGGER_PIN_ID,LOGIC_LOW);
}

/*Send the trigger pulse by using the Ultrasonic_Trigger
function.
Start the measurement process via the ICU driver.
return distance*/
uint16 Ultrasonic_readDistance(void){

	Ultrasonic_Trigger();

	uint16 distance=0;

	distance= (uint16)((float32)g_valueOfTime / 117);
	return distance;
}
