/*
 ============================================================================
 Name        : ultrasonic.h
 Author      : Menna Tullah Medhat
 Description : The ultrasonic sensor emits an ultrasonic wave and listens for
               its reflection from a nearby object
               initialization, turning LEDs on, and turning LEDs off.
 Date        : 13/6/2024
 ============================================================================
 */
/**************************************************************************************
 * 									DEFINITIONS									      *
 **************************************************************************************/

#include "std_types.h"
#include "gpio.h"

#define ULTRASONIC_TRIGGER_PIN_ID			PIN7_ID
#define ULTRASONIC_TRIGGER_PORT_ID			PORTD_ID
#define ULTRASONIC_ECHO_PIN_ID 				PIN6_ID
#define ULTRASONIC_ECHO_PORT_ID				PORTD_ID

#ifndef ULTRASONIC_H_
#define ULTRASONIC_H_

/**************************************************************************************
 * 								FUNCTION PROTOTYOES								      *
 **************************************************************************************/

/*Initialize the ICU driver as required.
Set up the ICU callback function.
Set the direction for the trigger pin as output through
the GPIO driver*/
void Ultrasonic_init(void);

/*Send the trigger pulse by using the Ultrasonic_Trigger
function.
Start the measurement process via the ICU driver.
return distance*/
uint16 Ultrasonic_readDistance(void);

/*This is the callback function called by the ICU driver.
It calculates the high time (pulse time) generated by
the ultrasonic sensor.*/
void Ultrasonic_edgeProcessing(void);

#endif /* ULTRASONIC_H_ */
